/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot6.gltf 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Model = React.forwardRef((props, ref) => {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/robot6.gltf')
  const { actions } = useAnimations(animations, group)

  // Function to make the robot look at a specific point
  const lookAt = (x, y, z) => {
    group.current.lookAt(x, y, z)
  }

  // Expose the lookAt function via ref
  React.useImperativeHandle(ref, () => ({
    lookAt
  }))

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.004']} position={[0.013, 0.424, -0.1]} rotation={[0, 1.552, 0]} scale={0.334} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.011']} position={[0.004, 0.395, 0.121]} rotation={[0, 1.552, 0]} scale={[0.091, 0.247, 0.26]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.002']} position={[0.426, 0.601, -0.087]} rotation={[Math.PI / 2, 0, -1.552]} scale={[0.04, 0.015, 0.219]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.003']} position={[-0.395, 0.599, -0.107]} rotation={[Math.PI / 2, 0, -1.552]} scale={[0.04, 0.015, 0.219]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.012']} position={[0.004, 0.557, 0.155]} rotation={[-0.814, 1.543, 0.813]} scale={[0.088, 0.036, 0.272]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.005']} position={[0.359, 0.424, -0.094]} rotation={[Math.PI / 2, 0, -1.552]} scale={[0.065, 0.02, 0.065]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.006']} position={[-0.33, 0.424, -0.107]} rotation={[Math.PI / 2, 0, -1.552]} scale={[0.065, 0.02, 0.065]} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['Material.007']} position={[-0.345, 0.423, -0.107]} rotation={[Math.PI / 2, 0, -1.552]} scale={[0.033, 0.021, 0.033]} />
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Material.009']} position={[0.375, 0.423, -0.093]} rotation={[Math.PI / 2, 0, -1.552]} scale={[0.033, 0.021, 0.033]} />
        <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Material.008']} position={[-0.39, 0.424, -0.106]} rotation={[-Math.PI / 2, 0, 1.552]} scale={[0.014, 0.031, 0.014]} />
        <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials['Material.010']} position={[0.414, 0.425, -0.085]} rotation={[-Math.PI / 2, 0, 1.552]} scale={[0.014, 0.031, 0.014]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.013']} morphTargetDictionary={nodes.Plane.morphTargetDictionary} morphTargetInfluences={nodes.Plane.morphTargetInfluences} position={[-0.068, 0.426, 0.212]} rotation={[0, 1.552, 1.571]} scale={[0.059, 1.164, 0.043]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Material} morphTargetDictionary={nodes.Plane001.morphTargetDictionary} morphTargetInfluences={nodes.Plane001.morphTargetInfluences} position={[0.004, 0.29, 0.212]} rotation={[Math.PI, -1.552, -1.555]} scale={[-0.023, -0.579, -0.115]} />
      </group>
    </group>
  )
})

useGLTF.preload('/robot6.gltf')

export default Model
